In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_excel('verzeo.xlsx')

In [3]:
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [4]:
df.isnull().sum()

Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
dtype: int64

In [5]:
del df['New_Price']

In [6]:
df.isnull().sum()

Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               2
Engine               36
Power                36
Seats                42
Price                 0
dtype: int64

In [7]:
df=df.dropna(axis=0,how='any')

In [8]:
df.isnull().sum()

Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

In [9]:
df.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'Price'],
      dtype='object')

In [11]:
df.dtypes

Name                  object
Location              object
Year                   int64
Kilometers_Driven      int64
Fuel_Type             object
Transmission          object
Owner_Type            object
Mileage               object
Engine                object
Power                 object
Seats                float64
Price                float64
dtype: object

In [12]:
df.shape

(5975, 12)

In [13]:
df.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'Price'],
      dtype='object')

In [14]:
len(set(df['Year']))

22

In [15]:
year_list=list(set(list(df['Year'])))

In [16]:
print(year_list)

[1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]

In [17]:
year_list=sorted(year_list)

In [18]:
print(year_list)

[1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]

In [19]:
year_number=[int(i) for i in range(1,23)]
print(year_number)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

In [20]:
year_dict=dict(zip(year_list,year_number))

In [21]:
print(year_dict)

{1998: 1, 1999: 2, 2000: 3, 2001: 4, 2002: 5, 2003: 6, 2004: 7, 2005: 8, 2006: 9, 2007: 10, 2008: 11, 2009: 12, 2010: 13, 2011: 14, 2012: 15, 2013: 16, 2014: 17, 2015: 18, 2016: 19, 2017: 20, 2018: 21, 2019: 22}

In [22]:
replaced_years=[]
for year in list(df['Year']):
    replaced_years.append(year_dict[year])

In [23]:
print(replaced_years[:10])

[13, 18, 14, 15, 16, 15, 16, 19, 16, 15]

In [24]:
engine_list=list(df['Engine'])

In [25]:
for i in range(len(engine_list)):
    engine_list[i]=float(engine_list[i][:-3])

In [26]:
print(engine_list)

[998.0, 1582.0, 1199.0, 1248.0, 1968.0, 814.0, 1461.0, 2755.0, 1598.0, 1248.0, 1462.0, 1497.0, 1248.0, 2179.0, 2179.0, 2477.0, 1498.0, 1248.0, 1461.0, 2143.0, 1995.0, 1248.0, 1984.0, 1197.0, 1598.0, 1497.0, 1461.0, 998.0, 1199.0, 2494.0, 1461.0, 1798.0, 2696.0, 2698.0, 1598.0, 1061.0, 1248.0, 1198.0, 2987.0, 1199.0, 796.0, 624.0, 1198.0, 1197.0, 1999.0, 1798.0, 1991.0, 2694.0, 1120.0, 2498.0, 1968.0, 1248.0, 1248.0, 1248.0, 1197.0, 1598.0, 799.0, 1197.0, 1995.0, 998.0, 2393.0, 1399.0, 1796.0, 2148.0, 1396.0, 1968.0, 1497.0, 1950.0, 1248.0, 1396.0, 4806.0, 2179.0, 1197.0, 1461.0, 1198.0, 1968.0, 1399.0, 1998.0, 2494.0, 1086.0, 1248.0, 1193.0, 1198.0, 1399.0, 1248.0, 1497.0, 1995.0, 1197.0, 1197.0, 1086.0, 1198.0, 2982.0, 1968.0, 1498.0, 2179.0, 1498.0, 1199.0, 1493.0, 998.0, 1598.0, 1396.0, 1197.0, 1198.0, 2967.0, 1197.0, 796.0, 1197.0, 2993.0, 2179.0, 1582.0, 2755.0, 1196.0, 624.0, 1995.0, 1799.0, 2494.0, 1984.0, 1198.0, 2497.0, 1248.0, 1086.0, 2143.0, 1582.0, 998.0, 624.0, 2179.0, 1796.0, 998.0, 2354.0, 1498.0, 1373.0, 2179.0, 1197.0, 998.0, 2996.0, 1591.0, 796.0, 1995.0, 1199.0, 1799.0, 2143.0, 1498.0, 1197.0, 1086.0, 2982.0, 1199.0, 1498.0, 1373.0, 2894.0, 1995.0, 1968.0, 1248.0, 5461.0, 1498.0, 1968.0, 814.0, 1199.0, 1198.0, 1198.0, 1595.0, 1498.0, 2494.0, 1197.0, 2179.0, 1498.0, 2982.0, 1498.0, 1399.0, 2993.0, 2143.0, 1198.0, 1197.0, 2143.0, 1197.0, 1968.0, 1598.0, 1998.0, 1396.0, 1968.0, 936.0, 1798.0, 1399.0, 1995.0, 1598.0, 1199.0, 1461.0, 2143.0, 1197.0, 1582.0, 1086.0, 1997.0, 2179.0, 1399.0, 1248.0, 1498.0, 1197.0, 1498.0, 1896.0, 1461.0, 1493.0, 1248.0, 1197.0, 1390.0, 1193.0, 1968.0, 1798.0, 1364.0, 1595.0, 1498.0, 1582.0, 1461.0, 1591.0, 998.0, 1796.0, 2967.0, 1086.0, 1598.0, 1798.0, 1197.0, 1498.0, 998.0, 1461.0, 2143.0, 998.0, 1461.0, 1248.0, 1998.0, 1396.0, 1199.0, 1199.0, 1248.0, 1399.0, 2755.0, 2199.0, 1497.0, 1197.0, 2143.0, 936.0, 1396.0, 2494.0, 1248.0, 2494.0, 1086.0, 1497.0, 1995.0, 1120.0, 1248.0, 1598.0, 1493.0, 1498.0, 1199.0, 1086.0, 1995.0, 2393.0, 796.0, 1197.0, 1197.0, 1248.0, 1582.0, 1086.0, 1197.0, 2987.0, 2148.0, 1248.0, 1582.0, 998.0, 1461.0, 1248.0, 2993.0, 1197.0, 2494.0, 993.0, 1248.0, 2179.0, 1248.0, 999.0, 1248.0, 796.0, 1497.0, 2967.0, 1896.0, 1591.0, 1497.0, 1396.0, 1396.0, 1598.0, 1497.0, 1248.0, 1995.0, 1061.0, 1199.0, 1896.0, 1197.0, 2143.0, 1197.0, 2393.0, 1968.0, 2494.0, 1198.0, 998.0, 1497.0, 1405.0, 1968.0, 2143.0, 1086.0, 1248.0, 998.0, 2143.0, 2179.0, 1598.0, 796.0, 1198.0, 2956.0, 1248.0, 998.0, 2179.0, 1396.0, 1373.0, 2354.0, 1248.0, 1399.0, 1497.0, 1968.0, 2993.0, 2967.0, 998.0, 1396.0, 1197.0, 1199.0, 1248.0, 1197.0, 1198.0, 796.0, 1794.0, 796.0, 1248.0, 796.0, 1968.0, 1794.0, 1197.0, 1248.0, 1497.0, 1248.0, 1498.0, 814.0, 1995.0, 1582.0, 1248.0, 1984.0, 998.0, 1498.0, 995.0, 1999.0, 1997.0, 1798.0, 1197.0, 1248.0, 1197.0, 1461.0, 1248.0, 1399.0, 993.0, 1998.0, 1364.0, 796.0, 796.0, 2993.0, 2496.0, 1197.0, 1248.0, 2967.0, 2143.0, 796.0, 1461.0, 1364.0, 2148.0, 1248.0, 1497.0, 1120.0, 2143.0, 1595.0, 2143.0, 1497.0, 1086.0, 1497.0, 1599.0, 1999.0, 1198.0, 1598.0, 2987.0, 814.0, 998.0, 1248.0, 1995.0, 2179.0, 1968.0, 2179.0, 2987.0, 2477.0, 796.0, 1061.0, 2179.0, 1591.0, 2993.0, 2993.0, 1798.0, 1968.0, 2179.0, 2143.0, 2179.0, 1995.0, 1497.0, 2400.0, 1495.0, 1197.0, 2996.0, 814.0, 1197.0, 1493.0, 1198.0, 1798.0, 1968.0, 1591.0, 1796.0, 1998.0, 1086.0, 1364.0, 1198.0, 1197.0, 1968.0, 814.0, 1461.0, 2993.0, 796.0, 1984.0, 998.0, 1497.0, 1196.0, 1399.0, 2523.0, 1086.0, 814.0, 1591.0, 1598.0, 1799.0, 1248.0, 2179.0, 1197.0, 1968.0, 1197.0, 1999.0, 2494.0, 793.0, 1248.0, 1968.0, 1995.0, 4134.0, 1197.0, 1461.0, 1120.0, 1498.0, 1198.0, 1120.0, 1248.0, 1497.0, 1086.0, 2494.0, 1248.0, 2982.0, 1596.0, 1950.0, 2148.0, 1968.0, 1197.0, 1196.0, 1395.0, 1461.0, 1999.0, 1399.0, 2953.0, 2982.0, 1199.0, 1248.0, 1461.0, 1582.0, 2497.0, 2987.0, 2354.0, 1582.0, 1086.0, 2143.0, 1373.0, 1896.0, 1198.0, 993.0, 1586.0, 1198.0, 998.0, 2362.0, 1199.0, 2982.0, 1498.0, 1248.0, 2987.0, 1497.0, 1197.0, 2179.0, 1598.0, 1086.0, 1591.0, 1997.0, 1598.0, 1461.0, 2993.0, 1496.0, 998.0, 1591.0, 998.0, 2179.0, 1199.0, 624.0, 1968.0, 2987.0, 1197.0, 1368.0, 1197.0, 2982.0, 1373.0, 1995.0, 1373.0, 1497.0, 2199.0, 1405.0, 2497.0, 1248.0, 1399.0, 1497.0, 2982.0, 1198.0, 1396.0, 1248.0, 1950.0, 1586.0, 2494.0, 1995.0, 1461.0, 1995.0, 1497.0, 1248.0, 1298.0, 2179.0, 1799.0, 1248.0, 1364.0, 1984.0, 1498.0, 1498.0, 1896.0, 1461.0, 2755.0, 1995.0, 1498.0, 1498.0, 2179.0, 1248.0, 1956.0, 1794.0, 1497.0, 1197.0, 1582.0, 2523.0, 1248.0, 1086.0, 1968.0, 1299.0, 1498.0, 2523.0, 1498.0, 1199.0, 1197.0, 1995.0, 1995.0, 2982.0, 4134.0, 1248.0, 1197.0, 3498.0, 1461.0, 1493.0, 2982.0, 2993.0, 1248.0, 1248.0, 1984.0, 2835.0, 2179.0, 2755.0, 1968.0, 1798.0, 796.0, 2143.0, 1498.0, 2179.0, 1461.0, 1582.0, 2993.0, 2179.0, 1582.0, 2967.0, 1150.0, 2523.0, 1197.0, 2393.0, 814.0, 1199.0, 1248.0, 1995.0, 814.0, 1497.0, 2354.0, 2498.0, 1995.0, 1497.0, 2179.0, 1396.0, 2982.0, 2523.0, 1298.0, 1086.0, 1496.0, 1968.0, 1197.0, 2179.0, 1498.0, 1968.0, 1197.0, 1197.0, 1995.0, 1299.0, 1197.0, 1582.0, 1995.0, 1796.0, 1199.0, 1086.0, 1405.0, 2179.0, 1248.0, 2143.0, 1497.0, 2982.0, 998.0, 1999.0, 1396.0, 1497.0, 1794.0, 1968.0, 2494.0, 1120.0, 1598.0, 2494.0, 1493.0, 1248.0, 2967.0, 1197.0, 1248.0, 1497.0, 1373.0, 1498.0, 1199.0, 1248.0, 1248.0, 2143.0, 1198.0, 1086.0, 1582.0, 1248.0, 1299.0, 1199.0, 1199.0, 1498.0, 1396.0, 1248.0, 1497.0, 1798.0, 1248.0, 1197.0, 998.0, 814.0, 1197.0, 3498.0, 1968.0, 1498.0, 1968.0, 2393.0, 1399.0, 1399.0, 1197.0, 2179.0, 1197.0, 3198.0, 1968.0, 1591.0, 2143.0, 2987.0, 1298.0, 1343.0, 1461.0, 2143.0, 2993.0, 1197.0, 1197.0, 1995.0, 796.0, 1968.0, 1598.0, 2967.0, 936.0, 998.0, 1461.0, 1995.0, 1197.0, 1968.0, 1499.0, 1197.0, 1248.0, 1599.0, 1995.0, 1186.0, 1497.0, 1248.0, 1248.0, 2179.0, 1495.0, 1248.0, 1248.0, 624.0, 1248.0, 998.0, 1248.0, 1598.0, 1896.0, 1496.0, 1396.0, 1086.0, 1497.0, 2179.0, 2143.0, 1991.0, 2179.0, 1796.0, 1199.0, 1496.0, 796.0, 1197.0, 998.0, 624.0, 1498.0, 1368.0, 1196.0, 1590.0, 1995.0, 1998.0, 2609.0, 1396.0, 1991.0, 2494.0, 2143.0, 1197.0, 2494.0, 2982.0, 1197.0, 1582.0, 1968.0, 1199.0, 1399.0, 1399.0, 998.0, 2143.0, 1591.0, 998.0, 2148.0, 1499.0, 1995.0, 2179.0, 796.0, 998.0, 2499.0, 1582.0, 1197.0, 1373.0, 2179.0, 1248.0, 3498.0, 1199.0, 2982.0, 2179.0, 2143.0, 1199.0, 1248.0, 1591.0, 3198.0, 1197.0, 1497.0, 1498.0, 1591.0, 1498.0, 1248.0, 998.0, 2446.0, 1197.0, 1896.0, 1197.0, 2993.0, 1995.0, 1399.0, 2143.0, 1968.0, 998.0, 799.0, 1498.0, 1199.0, 796.0, 1197.0, 1197.0, 1197.0, 1396.0, 998.0, 1396.0, 1197.0, 1399.0, 1197.0, 1120.0, 2179.0, 796.0, 1086.0, 1968.0, 2993.0, 998.0, 1598.0, 1995.0, 1248.0, 1399.0, 1198.0, 2967.0, 2393.0, 1582.0, 1086.0, 1968.0, 1968.0, 1896.0, 1997.0, 1582.0, 1498.0, 1197.0, 2494.0, 1197.0, 2523.0, 1498.0, 2179.0, 993.0, 2987.0, 2982.0, 1197.0, 1186.0, 1591.0, 1197.0, 1198.0, 2982.0, 1968.0, 2755.0, 1498.0, 1498.0, 999.0, 1248.0, 998.0, 2179.0, 1197.0, 1086.0, 1197.0, 1995.0, 1984.0, 1991.0, 1461.0, 998.0, 1248.0, 1498.0, 1248.0, 1495.0, 2609.0, 2143.0, 2982.0, 799.0, 1497.0, 2494.0, 1498.0, 1968.0, 1968.0, 1248.0, 2143.0, 1248.0, 1461.0, 1248.0, 1197.0, 1248.0, 814.0, 993.0, 1196.0, 1968.0, 1968.0, 799.0, 1248.0, 1978.0, 2993.0, 1497.0, 1396.0, 1197.0, 998.0, 2982.0, 2360.0, 1896.0, 3436.0, 1582.0, 1198.0, 1498.0, 1061.0, 1373.0, 1991.0, 1198.0, 1364.0, 1461.0, 998.0, 1198.0, 1582.0, 2993.0, 1956.0, 1999.0, 1248.0, 1248.0, 1586.0, 1582.0, 2477.0, 1198.0, 1197.0, 1493.0, 1248.0, 1198.0, 2393.0, 1197.0, 1498.0, 1197.0, 1396.0, 2143.0, 1197.0, 1197.0, 796.0, 1199.0, 1950.0, 1798.0, 1968.0, 2494.0, 2143.0, 1086.0, 1298.0, 1498.0, 1248.0, 1599.0, 1198.0, 998.0, 1199.0, 2198.0, 1197.0, 936.0, 1799.0, 998.0, 1598.0, 1590.0, 1498.0, 1495.0, 1995.0, 998.0, 1968.0, 1061.0, 1794.0, 2400.0, 1498.0, 1248.0, 1197.0, 2143.0, 1061.0, 1595.0, 1086.0, 1248.0, 1197.0, 1498.0, 998.0, 799.0, 1591.0, 1061.0, 1995.0, 1995.0, 1396.0, 1396.0, 796.0, 1248.0, 1498.0, 1198.0, 2393.0, 2179.0, 1197.0, 1582.0, 2179.0, 1498.0, 1248.0, 1368.0, 1248.0, 1199.0, 1497.0, 1396.0, 1497.0, 936.0, 995.0, 2179.0, 2987.0, 2993.0, 2755.0, 1995.0, 1461.0, 1120.0, 1995.0, 2497.0, 1198.0, 2179.0, 4367.0, 1368.0, 2354.0, 1197.0, 1120.0, 1461.0, 1968.0, 1197.0, 2494.0, 1197.0, 1498.0, 1497.0, 1497.0, 1199.0, 2143.0, 1498.0, 1396.0, 1248.0, 1248.0, 1461.0, 998.0, 1086.0, 936.0, 1997.0, 1086.0, 2179.0, 1197.0, 2755.0, 1896.0, 1197.0, 1364.0, 1248.0, 1396.0, 1498.0, 1248.0, 1248.0, 1497.0, 796.0, 3198.0, 1248.0, 2706.0, 1248.0, 1193.0, 1197.0, 1422.0, 1364.0, 1198.0, 1591.0, 1197.0, 1199.0, 2993.0, 1598.0, 1968.0, 1197.0, 998.0, 4134.0, 1248.0, 814.0, 1497.0, 1582.0, 998.0, 1197.0, 1497.0, 2494.0, 1493.0, 2179.0, 2967.0, 998.0, 1995.0, 1198.0, 796.0, 1591.0, 1199.0, 1197.0, 814.0, 1950.0, 1396.0, 1364.0, 1364.0, 1496.0, 1498.0, 1798.0, 2148.0, 1248.0, 1497.0, 2979.0, 1197.0, 1248.0, 1498.0, 796.0, 1968.0, 1248.0, 1120.0, 1248.0, 2143.0, 1248.0, 2497.0, 998.0, 1598.0, 1995.0, 2993.0, 1197.0, 2755.0, 1461.0, 1248.0, 1248.0, 1796.0, 2179.0, 2523.0, 1248.0, 1248.0, 1199.0, 1798.0, 2993.0, 998.0, 1086.0, 1798.0, 1197.0, 1198.0, 1197.0, 1248.0, 1197.0, 1197.0, 1199.0, 1248.0, 1193.0, 1598.0, 1298.0, 1197.0, 1197.0, 998.0, 2143.0, 1298.0, 1598.0, 1248.0, 1798.0, 1799.0, 1499.0, 1248.0, 1086.0, 2400.0, 1197.0, 1498.0, 2494.0, 799.0, 998.0, 1595.0, 998.0, 1248.0, 1591.0, 1582.0, 1497.0, 1086.0, 1364.0, 1969.0, 1399.0, 2987.0, 1995.0, 796.0, 2393.0, 999.0, 1598.0, 2477.0, 1799.0, 796.0, 1598.0, 2179.0, 1997.0, 1248.0, 2494.0, 1368.0, 2967.0, 1591.0, 1498.0, 1497.0, 1399.0, 1199.0, 1198.0, 1497.0, 1497.0, 998.0, 2354.0, 1995.0, 1489.0, 2179.0, 1598.0, 993.0, 796.0, 1798.0, 1997.0, 1299.0, 1199.0, 1364.0, 2179.0, 1120.0, 2143.0, 1197.0, 1798.0, 1798.0, 1968.0, 1396.0, 2143.0, 1248.0, 1582.0, 1999.0, 2489.0, 2494.0, 2494.0, 2967.0, 1248.0, 1248.0, 1197.0, 1197.0, 1197.0, 1197.0, 1495.0, 1198.0, 1248.0, 1197.0, 2179.0, 2143.0, 2179.0, 2143.0, 1396.0, 1968.0, 1497.0, 2982.0, 1968.0, 998.0, 1396.0, 1968.0, 796.0, 1497.0, 999.0, 2755.0, 1197.0, 1196.0, 1198.0, 1061.0, 1497.0, 1799.0, 1493.0, 1197.0, 1120.0, 1598.0, 1197.0, 1197.0, 1199.0, 1199.0, 1196.0, 1984.0, 1498.0, 1399.0, 2494.0, 1373.0, 1197.0, 999.0, 1798.0, 1248.0, 1298.0, 2993.0, 2494.0, 1248.0, 1968.0, 1995.0, 1197.0, 1995.0, 1496.0, 1405.0, 2987.0, 1984.0, 1598.0, 1120.0, 1248.0, 1396.0, 1995.0, 1497.0, 1968.0, 1248.0, 1343.0, 1242.0, 1995.0, 1388.0, 624.0, 1196.0, 1197.0, 1298.0, 1498.0, 1197.0, 1197.0, 2179.0, 1396.0, 998.0, 1396.0, 2993.0, 1598.0, 2967.0, 1497.0, 1197.0, 1498.0, 1198.0, 1248.0, 1248.0, 2354.0, 1794.0, 1590.0, 1497.0, 2179.0, 1798.0, 1995.0, 1586.0, 1373.0, 4367.0, 2494.0, 1086.0, 2199.0, 1796.0, 998.0, 796.0, 796.0, 1498.0, 796.0, 998.0, 1197.0, 1498.0, 1248.0, 1991.0, 1497.0, 1197.0, 1582.0, 1198.0, 1582.0, 1591.0, 998.0, 2354.0, 1497.0, 1248.0, 1498.0, 1396.0, 2987.0, 1461.0, 1461.0, 998.0, 1493.0, 1197.0, 1995.0, 1198.0, 1248.0, 1196.0, 1995.0, 1582.0, 1461.0, 1197.0, 1995.0, 1248.0, 1086.0, 2993.0, 1497.0, 2696.0, 1498.0, 796.0, 1198.0, 1199.0, 1199.0, 1248.0, 1498.0, 2755.0, 2497.0, 1248.0, 999.0, 1493.0, 1193.0, 2967.0, 1248.0, 1248.0, 1368.0, 1197.0, 814.0, 1086.0, 2143.0, 998.0, 1199.0, 1199.0, 1995.0, 1461.0, 1499.0, 2393.0, 936.0, 1798.0, 3198.0, 1582.0, 1196.0, 796.0, 1498.0, 2179.0, 1399.0, 1497.0, 1197.0, 2494.0, 1461.0, 2494.0, 1497.0, 998.0, 1198.0, 998.0, 1796.0, 1498.0, 1591.0, 1396.0, 1298.0, 2143.0, 1197.0, 1591.0, 1998.0, 1798.0, 998.0, 1461.0, 624.0, 1248.0, 1968.0, 1498.0, 1599.0, 1968.0, 1248.0, 2179.0, 1248.0, 1364.0, 1396.0, 796.0, 1198.0, 1999.0, 2982.0, 1197.0, 1197.0, 1998.0, 2987.0, 998.0, 1197.0, 1248.0, 2494.0, 2982.0, 1995.0, 1395.0, 2982.0, 1896.0, 1396.0, 1248.0, 1598.0, 1582.0, 1197.0, 1997.0, 2179.0, 1498.0, 1193.0, 2993.0, 1798.0, 998.0, 2354.0, 1197.0, 2982.0, 1796.0, 1248.0, 1248.0, 2993.0, 1598.0, 1799.0, 1995.0, 1968.0, 1248.0, 1984.0, 1298.0, 2179.0, 2354.0, 2494.0, 2982.0, 1199.0, 1497.0, 1248.0, 1461.0, 2494.0, 1198.0, 1598.0, 2179.0, 1498.0, 1968.0, 1197.0, 2494.0, 1248.0, 1248.0, 1498.0, 2393.0, 1591.0, 1497.0, 1498.0, 1598.0, 2967.0, 796.0, 1248.0, 1591.0, 2987.0, 2498.0, 1582.0, 1498.0, 1496.0, 796.0, 1461.0, 2143.0, 1461.0, 1248.0, 1198.0, 2179.0, 1198.0, 1197.0, 1598.0, 2494.0, 1498.0, 1198.0, 1248.0, 1197.0, 1582.0, 2967.0, 796.0, 1498.0, 1968.0, 1582.0, 998.0, 1999.0, 1497.0, 1991.0, 998.0, 1582.0, 1373.0, 1968.0, 1995.0, 1186.0, 2143.0, 2523.0, 1197.0, 1197.0, 1968.0, 1968.0, 2967.0, 2982.0, 1061.0, 814.0, 1198.0, 796.0, 2523.0, 1497.0, 1598.0, 1197.0, 814.0, 1197.0, 1198.0, 4134.0, 1248.0, 2179.0, 1498.0, 1497.0, 1497.0, 796.0, 1498.0, 1991.0, 2179.0, 1498.0, 1197.0, 998.0, 1968.0, 1373.0, 2179.0, 1150.0, 1373.0, 1396.0, 1199.0, 2179.0, 1197.0, 1582.0, 1086.0, 998.0, 1199.0, 1248.0, 1086.0, 1197.0, 1499.0, 2987.0, 1248.0, 796.0, 1298.0, 1591.0, 1995.0, 1299.0, 1498.0, 1373.0, 1968.0, 1498.0, 1968.0, 1120.0, 2987.0, 2494.0, 1498.0, 1968.0, 1399.0, 1498.0, 1248.0, 1198.0, 1598.0, 998.0, 1364.0, 1497.0, 1197.0, 1999.0, 2179.0, 1796.0, 1798.0, 1991.0, 2179.0, 1591.0, 1396.0, 1497.0, 1197.0, 1498.0, 998.0, 1198.0, 1197.0, 1598.0, 1896.0, 2143.0, 1598.0, 814.0, 1197.0, 1461.0, 2967.0, 1197.0, 1198.0, 1298.0, 1197.0, 2498.0, 1798.0, 998.0, 1199.0, 1197.0, 2143.0, 1591.0, 1172.0, 2494.0, 1493.0, 1498.0, 1995.0, 2987.0, 2987.0, 1197.0, 1798.0, 1197.0, 1396.0, 2179.0, 1198.0, 1197.0, 2499.0, 1493.0, 2982.0, 1995.0, 2982.0, 1199.0, 1086.0, 1197.0, 1995.0, 1968.0, 1197.0, 1197.0, 1495.0, 1197.0, 624.0, 1399.0, 1968.0, 1248.0, 2489.0, 998.0, 1496.0, 1197.0, 2494.0, 1405.0, 1995.0, 3198.0, 1462.0, 1498.0, 1150.0, 1497.0, 1498.0, 1197.0, 1399.0, 1248.0, 1197.0, 1248.0, 1498.0, 1248.0, 1197.0, 2953.0, 1199.0, 1493.0, 2993.0, 1461.0, 998.0, 1248.0, 796.0, 998.0, 1196.0, 1461.0, 1061.0, 1598.0, 1799.0, 2179.0, 1461.0, 999.0, 2967.0, 1248.0, 1198.0, 1197.0, 1995.0, 1248.0, 1197.0, 2996.0, 1998.0, 2987.0, 1248.0, 1796.0, 1197.0, 998.0, 1248.0, 1197.0, 1197.0, 1248.0, 1199.0, 1197.0, 1198.0, 1591.0, 1497.0, 1591.0, 2179.0, 998.0, 2494.0, 1248.0, 998.0, 1197.0, 1498.0, 1995.0, 1196.0, 1198.0, 1498.0, 1343.0, 2179.0, 2982.0, 1197.0, 1248.0, 1248.0, 1198.0, 1197.0, 1197.0, 2143.0, 998.0, 624.0, 1798.0, 1197.0, 1582.0, 1248.0, 814.0, 1968.0, 2494.0, 2987.0, 1120.0, 2354.0, 1498.0, 1197.0, 1582.0, 1399.0, 1197.0, 1582.0, 1197.0, 1968.0, 1298.0, 1197.0, 1198.0, 1582.0, 1956.0, 1248.0, 1798.0, 2179.0, 1995.0, 1396.0, 2987.0, 1998.0, 1197.0, 1198.0, 1461.0, 1198.0, 1197.0, 1991.0, 1086.0, 1248.0, 1498.0, 1595.0, 1197.0, 1197.0, 1248.0, 1343.0, 2494.0, 1998.0, 1368.0, 1399.0, 1086.0, 1120.0, 998.0, 1197.0, 1461.0, 1995.0, 1197.0, 999.0, 995.0, 1497.0, 1598.0, 2982.0, 1497.0, 1995.0, 1968.0, 1248.0, 1498.0, 1498.0, 1968.0, 1598.0, 2982.0, 1991.0, 1196.0, 1373.0, 1248.0, 2494.0, 1197.0, 2755.0, 1396.0, 1197.0, 1399.0, 1248.0, 1399.0, 2354.0, 1199.0, 2987.0, 1197.0, 1197.0, 1498.0, 1497.0, 1199.0, 1248.0, 1582.0, 2967.0, 814.0, 1399.0, 1198.0, 1461.0, 1199.0, 1197.0, 2967.0, 2696.0, 2755.0, 1896.0, 2148.0, 1373.0, 1248.0, 2446.0, 2495.0, 2835.0, 1794.0, 998.0, 796.0, 1968.0, 1197.0, 1498.0, 1796.0, 1968.0, 1197.0, 1248.0, 2179.0, 1199.0, 1498.0, 2993.0, 1968.0, 1995.0, 1197.0, 1582.0, 1968.0, 3498.0, 1197.0, 1498.0, 1598.0, 1248.0, 1997.0, 1396.0, 796.0, 1197.0, 2179.0, 1199.0, 2993.0, 1498.0, 2148.0, 2179.0, 1497.0, 1248.0, 2143.0, 1497.0, 2956.0, 1197.0, 1248.0, 1799.0, 1582.0, 1968.0, 1591.0, 1396.0, 1498.0, 1582.0, 1596.0, 1197.0, 1248.0, 2494.0, 2143.0, 796.0, 2143.0, 1248.0, 1197.0, 2982.0, 1998.0, 1498.0, 1196.0, 2982.0, 1197.0, 2979.0, 1798.0, 1061.0, 1461.0, 1373.0, 1582.0, 1498.0, 2143.0, 2354.0, 998.0, 2979.0, 1995.0, 1598.0, 1248.0, 2179.0, 1396.0, 1248.0, 1956.0, 1248.0, 1196.0, 1364.0, 1248.0, 1497.0, 2179.0, 1197.0, 2148.0, 1390.0, 1896.0, 2987.0, 1995.0, 1598.0, 1968.0, 1399.0, 1582.0, 2393.0, 1197.0, 1198.0, 799.0, 1497.0, 1197.0, 999.0, 1248.0, 1461.0, 2179.0, 1248.0, 1968.0, 1196.0, 2199.0, 2179.0, 1461.0, 1968.0, 1196.0, 2498.0, 998.0, 1061.0, 1586.0, 2393.0, 2494.0, 1199.0, 1496.0, 1498.0, 1120.0, 1497.0, 2494.0, 814.0, 1197.0, 1796.0, 2523.0, 1968.0, 1197.0, 1968.0, 1399.0, 1586.0, 1197.0, 1197.0, 2179.0, 2179.0, 796.0, 1461.0, 2498.0, 1197.0, 2494.0, 2993.0, 1991.0, 1461.0, 998.0, 1968.0, 1956.0, 1396.0, 1198.0, 1582.0, 1086.0, 1493.0, 1298.0, 1495.0, 2179.0, 998.0, 1199.0, 2698.0, 1496.0, 1193.0, 1498.0, 1199.0, 1968.0, 1498.0, 1582.0, 1497.0, 1197.0, 1995.0, 1968.0, 2354.0, 1197.0, 1248.0, 1497.0, 2993.0, 998.0, 1995.0, 1399.0, 2494.0, 1248.0, 2996.0, 1950.0, 1197.0, 1497.0, 4806.0, 1493.0, 1794.0, 1198.0, 2497.0, 796.0, 1968.0, 1364.0, 2179.0, 2982.0, 1193.0, 2143.0, 1582.0, 1497.0, 1968.0, 993.0, 796.0, 1197.0, 2179.0, 1194.0, 1197.0, 2143.0, 1497.0, 1499.0, 1197.0, 1197.0, 2494.0, 1197.0, 2967.0, 2199.0, 999.0, 1497.0, 1396.0, 2523.0, 2755.0, 2497.0, 1995.0, 998.0, 1248.0, 1999.0, 1248.0, 1396.0, 998.0, 814.0, 2953.0, 2198.0, 1598.0, 1373.0, 814.0, 1968.0, 2179.0, 1248.0, 1248.0, 2143.0, 1461.0, 1197.0, 2494.0, 1591.0, 1248.0, 2179.0, 1497.0, 2179.0, 1399.0, 2497.0, 1248.0, 1968.0, 1198.0, 1497.0, 1198.0, 2179.0, 1497.0, 1598.0, 2179.0, 1896.0, 1197.0, 1498.0, 1598.0, 796.0, 2993.0, 1497.0, 1461.0, 796.0, 2755.0, 1396.0, 1399.0, 1248.0, 1582.0, 1999.0, 1248.0, 1984.0, 2143.0, 1461.0, 1198.0, 1984.0, 1197.0, 998.0, 796.0, 1248.0, 1498.0, 2494.0, 998.0, 2987.0, 1197.0, 1199.0, 2179.0, 1198.0, 1197.0, 2362.0, 998.0, 1995.0, 998.0, 2143.0, 796.0, 1197.0, 1199.0, 1396.0, 2496.0, 1364.0, 2982.0, 1598.0, 1198.0, 1198.0, 1198.0, 998.0, 1364.0, 2179.0, 1197.0, 1498.0, 1373.0, 1497.0, 1497.0, 998.0, 1598.0, 2755.0, 1197.0, 1248.0, 1968.0, 1598.0, 1799.0, 1199.0, 1968.0, 1197.0, 2755.0, 2143.0, 1396.0, 1197.0, 1598.0, 1197.0, 1248.0, 1497.0, 1582.0, 1498.0, 796.0, 1197.0, 2987.0, 796.0, 1196.0, 2393.0, 1995.0, 2199.0, 1995.0, 1399.0, 1364.0, 2179.0, 796.0, 2982.0, 2446.0, 1499.0, 1197.0, 1998.0, 1591.0, 1399.0, 1498.0, 1461.0, 1498.0, 2993.0, 2755.0, 1086.0, 2696.0, 998.0, 1197.0, 999.0, 1248.0, 1968.0, 1198.0, 1499.0, 998.0, 2967.0, 1968.0, 1248.0, 1461.0, 1462.0, 624.0, 1497.0, 1196.0, 1396.0, 1499.0, 1968.0, 1995.0, 2179.0, 2179.0, 1591.0, 1497.0, 1995.0, 3436.0, 2993.0, 796.0, 1197.0, 1999.0, 1248.0, 2993.0, 2499.0, 1498.0, 1497.0, 1197.0, 1968.0, 1197.0, 2179.0, 2987.0, 998.0, 1598.0, 624.0, 1197.0, 1498.0, 1999.0, 1248.0, 2993.0, 1498.0, 1198.0, 1598.0, 2696.0, 1461.0, 2755.0, 1794.0, 1197.0, 1396.0, 1498.0, 1582.0, 2143.0, 1498.0, 999.0, 1197.0, 1248.0, 2489.0, 1498.0, 2179.0, 1199.0, 1591.0, 1197.0, 1461.0, 1197.0, 1197.0, 1991.0, 2148.0, 1991.0, 1582.0, 2489.0, 1248.0, 1197.0, 2179.0, 1197.0, 1998.0, 1794.0, 1798.0, 2393.0, 1997.0, 1998.0, 998.0, 1248.0, 1199.0, 1197.0, 998.0, 998.0, 998.0, 1498.0, 814.0, 1598.0, 1248.0, 2143.0, 1968.0, 1248.0, 1086.0, 1120.0, 1248.0, 1197.0, 2179.0, 1798.0, 1373.0, 1582.0, 1364.0, 1497.0, 2198.0, 1396.0, 1497.0, 1197.0, 1298.0, 1199.0, 2400.0, 1197.0, 2143.0, 799.0, 1196.0, 2982.0, 1497.0, 2523.0, 1995.0, 1248.0, 1796.0, 1591.0, 1186.0, 1498.0, 1198.0, 2354.0, 1086.0, 2143.0, 1198.0, 2982.0, 1591.0, 2993.0, 1995.0, 1396.0, 1399.0, 1061.0, 1197.0, 2179.0, 2143.0, 1197.0, 2982.0, 2494.0, 1399.0, 1197.0, 1197.0, 1086.0, 1193.0, 1248.0, 1497.0, 1248.0, 1197.0, 814.0, 1498.0, 936.0, 1995.0, 2143.0, 998.0, 1197.0, 1086.0, 1405.0, 1248.0, 1186.0, 1461.0, 1591.0, 2755.0, 1197.0, 1461.0, 1198.0, 1498.0, 1598.0, 1461.0, 1968.0, 2494.0, 1193.0, 2982.0, 1995.0, 1598.0, 1497.0, 1248.0, 1995.0, 1198.0, 1197.0, 1248.0, 2143.0, 1498.0, 2494.0, 2993.0, 1496.0, 936.0, 2354.0, 796.0, 1968.0, 2494.0, 1968.0, 1248.0, 1197.0, 1794.0, 2179.0, 1197.0, 1591.0, 796.0, 796.0, 2143.0, 1086.0, 1798.0, 1498.0, 1248.0, 1799.0, 1995.0, 1086.0, 1248.0, 2354.0, 1248.0, 1388.0, 2967.0, 1968.0, 1248.0, 1493.0, 1950.0, 1995.0, 1120.0, 1197.0, 1197.0, 1086.0, 2993.0, 1586.0, 1396.0, 1248.0, 1248.0, 1968.0, 1461.0, 2179.0, 1995.0, 1061.0, 1061.0, 1197.0, 1086.0, 2993.0, 1796.0, 1461.0, 2967.0, 2143.0, 1248.0, 1248.0, 1498.0, 2967.0, 998.0, 1498.0, 814.0, 2987.0, 1995.0, 1995.0, 1493.0, 1197.0, 2993

In [28]:
power_list=list(df['Power'])

In [29]:
invalid_power_indices=[]

In [30]:
for i in range(len(power_list)):
    try:
        power_list[i]=float(power_list[i][:-4])
    except:
        invalid_power_indices.append(i)

In [31]:
print(power_list[:50])

[58.16, 126.2, 88.7, 88.76, 140.8, 55.2, 63.1, 171.5, 103.6, 74.0, 103.25, 116.3, 74.0, 187.7, 115.0, 175.56, 98.6, 74.0, 83.8, 167.62, 190.0, 88.5, 177.01, 80.0, 103.6, 116.3, 63.1, 67.1, 88.7, 102.0, 108.45, 138.1, 184.0, 179.5, 103.5, 64.0, 88.5, 82.0, 254.8, 73.9, 46.3, 37.5, 77.0, 82.9, 149.92, 138.03, 112.2, 163.7, 71.0, 105.0]

In [32]:
print(invalid_power_indices)

[76, 79, 89, 120, 143, 225, 242, 259, 304, 305, 383, 421, 425, 440, 469, 572, 628, 644, 645, 735, 744, 824, 910, 921, 929, 1063, 1138, 1148, 1266, 1313, 1338, 1380, 1411, 1546, 1569, 1640, 1663, 1848, 1989, 2043, 2118, 2152, 2250, 2254, 2292, 2328, 2377, 2425, 2434, 2481, 2485, 2511, 2561, 2579, 2616, 2621, 2868, 3010, 3038, 3081, 3166, 3224, 3266, 3414, 3491, 3506, 3562, 3601, 3611, 3618, 3642, 3706, 3868, 3900, 3969, 4046, 4049, 4318, 4321, 4593, 4672, 4676, 4706, 4792, 4848, 4862, 4914, 5024, 5078, 5186, 5383, 5395, 5415, 5486, 5490, 5604, 5712, 5716, 5818, 5830, 5881, 5899, 5941]

In [33]:
df.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'Price'],
      dtype='object')

In [35]:
seats_list=list(df['Seats'])
for i in range(len(seats_list)):
    seats_list[i]=float(seats_list[i])

In [36]:
print(seats_list[:10])

[5.0, 5.0, 5.0, 7.0, 5.0, 5.0, 5.0, 8.0, 5.0, 5.0]

In [47]:
mileage_list=list(df['Mileage'])
for i in range(len(mileage_list)):
    mileage_list[i]=float(mileage_list[i][:-6])

In [48]:
print(mileage_list[:10])

[26.6, 19.6, 18.0, 20.7, 15.0, 21.1, 23.0, 11.3, 20.5, 22.0]

In [49]:
kilometers_list=list(df['Kilometers_Driven'])
for i in range(len(kilometers_list)):
    kilometers_list[i]=float(kilometers_list[i])

In [50]:
print(kilometers_list[:10])

[72000.0, 41000.0, 46000.0, 87000.0, 40670.0, 75000.0, 86999.0, 36000.0, 64430.0, 65932.0]

In [51]:
price_list=list(df['Price'])
for i in range(len(price_list)):
    price_list[i]=float(price_list[i])

In [52]:
print(price_list)

[1.75, 12.5, 4.5, 6.0, 17.74, 2.35, 3.5, 17.5, 5.2, 1.95, 9.95, 4.49, 5.6, 27.0, 17.5, 15.0, 5.4, 5.99, 6.34, 28.0, 18.55, 8.25, 23.5, 1.87, 2.85, 4.25, 4.25, 2.75, 9.9, 4.0, 7.75, 6.75, 12.5, 11.5, 6.98, 1.85, 8.63, 4.85, 28.0, 5.0, 1.25, 1.53, 5.58, 4.74, 8.85, 10.11, 4.25, 10.95, 3.85, 5.5, 21.43, 4.25, 3.3, 3.85, 3.6, 3.99, 3.3, 2.07, 7.75, 2.25, 16.5, 2.75, 26.7, 10.0, 2.5, 13.5, 1.85, 35.67, 8.15, 10.5, 14.5, 9.65, 3.48, 6.92, 6.46, 29.5, 2.0, 4.5, 11.75, 1.3, 3.75, 4.5, 4.82, 2.8, 3.11, 3.25, 13.9, 2.25, 5.75, 2.1, 5.0, 16.5, 39.58, 5.5, 8.1, 3.5, 2.79, 3.45, 4.45, 2.65, 3.8, 4.65, 3.95, 9.8, 2.7, 2.41, 3.9, 24.0, 5.75, 5.25, 19.25, 3.91, 2.15, 20.75, 3.35, 11.11, 20.0, 6.55, 7.0, 7.5, 0.85, 16.75, 10.95, 2.45, 3.23, 7.75, 9.35, 3.25, 5.25, 7.25, 7.47, 13.25, 5.81, 2.6, 54.0, 11.5, 1.6, 17.22, 6.0, 3.95, 17.95, 3.7, 5.43, 1.67, 13.49, 2.85, 4.75, 9.9, 37.0, 26.5, 23.32, 6.25, 30.0, 9.86, 8.5, 4.23, 3.5, 2.5, 2.39, 11.25, 7.11, 10.9, 6.2, 7.9, 4.42, 13.5, 6.25, 2.1, 45.0, 33.66, 3.65, 2.75, 42.5, 6.5, 19.0, 4.45, 23.0, 8.35, 22.95, 1.5, 6.89, 1.45, 33.5, 1.25, 4.2, 6.75, 32.0, 7.5, 4.6, 4.04, 10.31, 55.76, 2.6, 8.5, 3.5, 3.55, 3.25, 4.5, 5.35, 6.5, 9.0, 6.0, 2.75, 1.5, 19.9, 10.0, 3.0, 11.96, 3.25, 4.75, 5.95, 8.15, 4.22, 10.5, 45.0, 2.9, 8.9, 26.0, 8.22, 3.5, 1.25, 3.7, 39.41, 2.65, 8.92, 4.1, 35.67, 0.85, 3.32, 3.6, 6.8, 2.5, 19.64, 7.0, 3.87, 6.27, 18.12, 2.65, 7.2, 14.3, 6.9, 10.75, 0.95, 8.09, 18.5, 4.75, 8.45, 3.5, 1.8, 3.7, 7.17, 1.75, 21.99, 18.65, 1.85, 5.95, 3.75, 3.75, 2.6, 1.75, 2.8, 61.29, 18.0, 4.35, 13.75, 2.0, 10.0, 1.65, 45.77, 3.25, 12.8, 0.55, 7.15, 7.0, 3.75, 8.5, 4.35, 3.26, 4.21, 70.36, 2.95, 4.28, 3.57, 3.11, 5.96, 4.7, 6.9, 5.25, 28.0, 1.35, 4.85, 6.7, 3.1, 18.64, 2.8, 20.25, 26.78, 8.26, 3.89, 2.1, 12.69, 2.58, 20.77, 20.26, 1.5, 2.5, 4.25, 57.0, 44.0, 3.65, 2.05, 3.13, 1.5, 2.85, 2.65, 10.6, 1.25, 8.25, 4.45, 3.7, 2.8, 1.8, 21.95, 49.0, 62.67, 1.4, 5.5, 2.95, 6.86, 6.15, 3.3, 2.55, 1.5, 2.5, 1.4, 3.4, 2.25, 7.5, 2.8, 7.66, 7.15, 3.5, 3.5, 3.45, 3.55, 25.99, 5.25, 2.9, 2.05, 3.75, 6.75, 0.95, 52.0, 3.91, 27.3, 2.7, 3.5, 6.2, 2.75, 3.25, 3.25, 0.65, 35.0, 3.25, 2.9, 2.9, 17.75, 8.25, 5.77, 9.49, 12.95, 20.0, 1.0, 7.1, 16.5, 26.0, 3.2, 9.48, 4.0, 26.5, 11.77, 37.0, 8.75, 1.95, 3.75, 2.5, 34.5, 4.65, 32.0, 62.81, 3.25, 3.1, 3.91, 11.0, 3.5, 16.5, 30.0, 28.0, 28.0, 0.92, 2.75, 53.83, 4.95, 33.5, 27.95, 7.25, 25.71, 29.67, 19.0, 13.05, 25.5, 8.5, 7.25, 0.8, 6.9, 70.99, 2.25, 5.5, 4.35, 2.25, 24.5, 5.45, 12.03, 8.5, 28.5, 1.2, 5.75, 3.2, 9.89, 6.58, 4.06, 13.37, 25.82, 3.74, 22.0, 1.45, 2.0, 4.7, 3.75, 7.7, 3.35, 2.6, 13.77, 7.1, 2.65, 2.5, 7.53, 7.98, 39.0, 2.25, 3.85, 13.5, 3.5, 8.92, 20.37, 36.5, 48.91, 7.2, 5.99, 5.25, 6.5, 4.4, 4.6, 2.95, 3.26, 2.22, 10.5, 8.26, 14.45, 2.5, 51.43, 23.0, 5.5, 4.5, 6.8, 8.75, 7.0, 33.5, 2.25, 4.24, 28.42, 2.75, 3.0, 3.55, 4.8, 13.5, 56.0, 3.99, 15.5, 2.32, 18.58, 5.5, 3.2, 4.0, 1.6, 4.15, 4.25, 2.6, 3.43, 2.55, 32.0, 6.25, 3.6, 18.5, 4.25, 4.8, 13.0, 2.25, 2.3, 13.56, 12.25, 3.76, 8.58, 27.5, 4.95, 3.3, 8.0, 2.79, 45.64, 2.55, 1.0, 37.56, 9.29, 6.37, 2.98, 5.75, 13.0, 6.8, 10.49, 5.6, 2.85, 8.36, 1.0, 10.75, 3.85, 3.0, 9.6, 13.25, 5.75, 6.75, 4.85, 38.99, 2.85, 9.51, 18.5, 6.75, 29.4, 3.29, 9.5, 2.2, 6.5, 4.9, 6.75, 3.8, 29.5, 10.5, 6.2, 5.0, 2.3, 17.0, 25.5, 5.65, 5.6, 29.98, 7.39, 19.0, 5.0, 3.35, 4.45, 8.31, 6.0, 5.25, 1.4, 12.3, 1.5, 8.12, 6.12, 10.88, 3.5, 6.15, 33.0, 13.5, 17.11, 29.77, 5.95, 5.75, 19.0, 4.75, 3.3, 16.5, 44.0, 4.39, 6.2, 24.22, 5.45, 44.0, 24.82, 11.69, 20.0, 1.45, 48.5, 9.45, 12.5, 6.9, 5.8, 44.56, 8.5, 10.7, 12.0, 2.44, 1.95, 4.35, 17.5, 2.9, 2.9, 8.9, 16.75, 3.95, 2.1, 4.29, 3.85, 9.0, 4.5, 12.46, 4.65, 20.5, 2.9, 1.45, 0.65, 29.5, 25.0, 3.5, 11.25, 10.79, 5.9, 5.12, 5.7, 35.84, 1.25, 2.65, 9.19, 23.5, 12.5, 1.5, 0.8, 0.75, 8.1, 9.75, 37.93, 1.96, 20.5, 2.75, 75.0, 2.8, 9.25, 3.0, 23.89, 12.75, 4.15, 4.65, 8.9, 1.5, 3.27, 18.0, 6.3, 11.31, 6.16, 6.0, 5.43, 4.65, 7.5, 6.25, 9.25, 3.15, 2.3, 5.25, 7.4, 1.55, 6.0, 5.9, 4.7, 6.5, 3.55, 7.1, 6.0, 7.99, 4.1, 3.95, 4.38, 2.75, 55.54, 29.0, 6.6, 6.99, 18.75, 1.28, 1.2, 4.31, 16.5, 5.64, 31.12, 25.46, 7.88, 36.0, 30.0, 2.85, 3.5, 7.5, 19.0, 54.0, 4.7, 8.5, 17.0, 3.51, 19.5, 17.0, 43.35, 2.65, 3.52, 6.25, 24.75, 5.25, 11.0, 9.1, 3.25, 8.5, 3.1, 19.86, 4.9, 5.7, 2.9, 7.83, 8.15, 2.0, 6.25, 3.4, 3.19, 7.75, 3.2, 4.9, 3.8, 4.0, 23.5, 1.15, 2.2, 10.65, 35.68, 31.94, 4.2, 9.9, 15.46, 8.46, 3.25, 2.6, 5.2, 1.8, 1.6, 2.5, 2.5, 6.7, 1.2, 35.55, 7.75, 1.94, 2.2, 3.8, 15.65, 39.47, 1.5, 8.85, 17.9, 5.08, 6.25, 22.75, 1.46, 2.05, 4.08, 4.55, 14.0, 10.9, 2.45, 15.8, 8.25, 8.5, 15.54, 2.35, 4.32, 3.9, 5.2, 5.85, 6.25, 17.63, 9.75, 55.0, 4.1, 11.99, 13.54, 56.0, 6.5, 4.75, 5.6, 29.2, 6.35, 4.95, 8.5, 4.5, 5.5, 6.56, 2.3, 3.5, 4.55, 7.75, 5.25, 23.29, 23.99, 1.79, 13.9, 18.95, 2.49, 3.15, 6.45, 4.25, 2.75, 7.14, 2.44, 3.5, 7.3, 2.75, 8.2, 6.51, 4.25, 6.21, 4.58, 7.5, 2.1, 4.09, 10.75, 41.5, 4.4, 6.25, 10.5, 7.25, 3.2, 3.95, 12.07, 18.6, 5.7, 1.75, 10.99, 14.5, 3.11, 13.96, 7.11, 6.9, 7.77, 5.5, 5.35, 4.5, 4.75, 32.8, 0.7, 50.29, 10.99, 5.57, 5.9, 9.43, 2.9, 3.68, 21.67, 12.5, 19.92, 6.75, 6.96, 3.25, 8.65, 5.0, 5.5, 2.6, 3.41, 2.7, 5.5, 35.0, 9.75, 4.25, 3.2, 6.85, 4.5, 3.55, 1.9, 3.6, 21.8, 13.5, 2.66, 3.75, 32.0, 8.07, 5.64, 23.99, 7.5, 27.0, 2.85, 6.35, 3.3, 5.0, 6.46, 3.75, 1.52, 3.61, 43.74, 20.0, 3.0, 3.65, 5.25, 58.0, 8.65, 2.5, 7.75, 4.15, 10.85, 5.53, 11.5, 40.0, 9.25, 2.29, 7.0, 1.65, 8.25, 9.14, 6.5, 2.95, 5.75, 2.85, 2.1, 13.55, 20.5, 20.0, 59.72, 6.5, 7.5, 2.15, 8.44, 12.49, 5.48, 4.2, 7.2, 4.8, 5.83, 18.39, 5.85, 6.21, 3.65, 3.7, 30.0, 4.85, 6.93, 2.6, 1.89, 39.5, 10.0, 9.95, 9.45, 28.25, 1.8, 1.4, 7.25, 3.6, 1.2, 4.94, 1.25, 4.8, 31.15, 3.3, 2.4, 2.0, 3.1, 5.09, 1.05, 7.0, 2.5, 17.5, 2.1, 17.75, 1.45, 2.45, 13.8, 5.85, 8.9, 5.15, 16.56, 1.65, 16.0, 1.45, 8.08, 4.5, 4.3, 2.6, 4.45, 5.37, 1.75, 16.5, 19.0, 2.8, 6.2, 3.8, 6.1, 11.65, 4.15, 16.5, 4.3, 2.25, 6.75, 9.4, 5.39, 8.51, 1.85, 2.5, 4.75, 3.5, 5.5, 6.33, 2.47, 3.3, 3.5, 38.75, 7.99, 13.28, 9.5, 14.01, 6.99, 11.0, 11.0, 2.3, 26.5, 67.0, 17.75, 4.8, 4.57, 3.5, 7.61, 25.0, 5.88, 13.5, 4.6, 4.9, 5.25, 12.41, 3.8, 8.95, 7.2, 4.5, 4.15, 7.94, 7.25, 3.7, 2.45, 1.5, 12.0, 2.2, 3.6, 1.92, 20.5, 4.25, 3.2, 2.6, 3.85, 3.48, 4.55, 7.0, 5.75, 8.73, 1.7, 29.5, 10.49, 64.0, 7.55, 3.95, 3.25, 2.75, 7.35, 4.7, 8.77, 3.42, 2.5, 20.0, 5.25, 14.5, 3.45, 3.3, 51.0, 6.5, 3.65, 7.25, 6.01, 2.8, 4.0, 5.95, 9.2, 5.35, 12.0, 38.94, 2.69, 27.5, 2.75, 2.8, 6.45, 5.88, 4.65, 2.5, 51.35, 6.85, 5.25, 9.23, 22.0, 5.19, 4.35, 24.5, 5.75, 9.19, 10.75, 2.99, 3.89, 11.73, 3.11, 14.45, 8.7, 5.04, 8.5, 15.65, 5.65, 16.5, 2.0, 3.9, 14.5, 44.0, 5.0, 19.75, 11.44, 1.75, 5.6, 30.42, 9.57, 3.5, 10.46, 4.85, 5.68, 13.25, 16.0, 3.0, 0.99, 5.0, 4.75, 5.35, 5.98, 3.5, 4.77, 5.45, 6.85, 7.3, 1.25, 8.25, 2.71, 3.6, 3.0, 4.65, 9.5, 2.95, 3.0, 5.95, 4.0, 2.5, 11.37, 2.25, 3.1, 17.18, 6.5, 5.7, 8.0, 2.6, 2.45, 11.57, 2.3, 5.9, 7.2, 5.9, 6.0, 1.95, 6.55, 25.0, 2.65, 69.5, 14.0, 2.1, 20.4, 5.68, 5.55, 12.75, 3.35, 1.55, 5.9, 18.98, 11.51, 7.75, 13.9, 1.35, 38.0, 11.6, 12.25, 3.8, 3.25, 6.4, 3.95, 3.57, 1.25, 3.65, 12.5, 23.0, 1.35, 6.32, 3.4, 0.77, 0.9, 18.0, 19.0, 1.1, 2.0, 6.5, 9.45, 4.0, 32.25, 2.1, 9.75, 6.3, 21.0, 4.65, 17.0, 4.35, 14.82, 40.0, 6.15, 11.25, 32.0, 45.62, 6.24, 4.8, 4.5, 3.87, 2.75, 6.57, 2.0, 3.65, 6.95, 5.5, 7.0, 24.0, 11.0, 32.5, 6.45, 15.75, 5.5, 19.03, 15.25, 2.4, 2.3, 14.35, 3.5, 11.97, 1.6, 18.9, 5.4, 2.95, 5.1, 1.5, 4.9, 2.9, 1.15, 2.3, 5.99, 3.4, 1.7, 1.99, 2.5, 4.85, 2.65, 27.35, 6.9, 3.5, 12.5, 9.2, 4.9, 5.55, 13.5, 2.6, 4.5, 34.0, 12.0, 5.25, 21.56, 24.68, 3.67, 29.5, 3.1, 2.9, 43.0, 15.95, 4.5, 3.49, 4.25, 1.9, 16.57, 5.75, 14.0, 2.5, 1.2, 0.85, 13.95, 1.6, 3.6, 4.5, 6.06, 5.29, 5.75, 5.72, 4.39, 11.05, 4.83, 2.96, 4.5, 19.5, 8.75, 67.0, 8.4, 4.99, 8.18, 2.9, 7.1, 7.05, 17.5, 3.41, 1.3, 5.68, 4.1, 4.0, 30.0, 1.8, 6.93, 70.0, 7.9, 2.78, 14.4, 13.5, 3.15, 2.88, 2.15, 3.75, 3.6, 3.6, 7.55, 4.7, 1.6, 3.34, 9.1, 6.17, 2.5, 3.0, 5.75, 10.75, 2.85, 6.5, 9.45, 6.75, 7.75, 4.4, 42.0, 5.67, 11.5, 1.69, 1.8, 3.2, 45.86, 5.1, 4.85, 2.4, 22.0, 4.28, 5.67, 6.2, 14.49, 3.0, 2.25, 43.78, 11.45, 10.5, 7.48, 3.1, 2.55, 3.5, 2.59, 5.45, 6.0, 15.49, 12.5, 4.75, 7.85, 6.0, 4.0, 28.75, 2.5, 5.5, 1.59, 6.22, 2.75, 1.35, 25.0, 2.8, 2.45, 6.35, 8.0, 8.25, 5.95, 19.92, 3.15, 5.75, 32.44, 8.01, 6.48, 0.75, 5.0, 7.75, 2.6, 9.2, 5.05, 9.6, 5.5, 9.35, 2.6, 3.5, 4.26, 4.25, 11.75, 3.5, 7.5, 3.25, 4.9, 27.0, 8.91, 6.69, 6.02, 4.5, 2.0, 2.4, 1.2, 2.9, 27.0, 7.5, 1.5, 39.5, 3.39, 12.4, 6.85, 5.75, 2.0, 0.9, 3.8, 16.35, 16.5, 8.7, 6.1, 21.94, 22.0, 2.65, 5.27, 2.48, 6.0, 8.9, 18.0, 11.64, 8.99, 5.25, 2.95, 2.65, 4.0, 12.5, 3.25, 4.0, 6.25, 5.8, 5.0, 58.73, 17.49, 1.95, 3.0, 5.5, 16.5, 14.5, 7.79, 8.27, 97.07, 2.15, 3.0, 28.79, 5.45, 3.95, 16.0, 4.25, 34.5, 2.6, 13.48, 32.1, 6.17, 5.5, 9.15, 4.5, 10.5, 5.37, 5.45, 9.25, 7.7, 7.99, 3.0, 4.0, 6.69, 4.25, 10.5, 22.55, 5.2, 11.87, 6.99, 5.0, 44.0, 2.79, 2.9, 9.85, 49.0, 9.25, 3.75, 7.29, 23.5, 2.6, 3.1, 29.98, 6.73, 3.5, 2.35, 16.13, 5.9, 3.9, 1.5, 6.95, 7.0, 7.23, 3.81, 4.5, 12.6, 48.0, 2.96, 3.25, 8.5, 8.75, 3.08, 41.5, 7.0, 11.5, 2.6, 4.3, 8.35, 24.9, 13.75, 3.85, 23.25, 7.0, 5.75, 1.65, 6.5, 7.5, 72.94, 11.0, 3.02, 3.32, 3.24, 2.35, 5.5, 6.75, 6.15, 5.45, 2.3, 6.21, 5.21, 11.99, 3.1, 7.5, 4.0, 7.73, 7.8, 1.3, 4.42, 4.0, 13.0, 5.38, 3.25, 3.87, 8.25, 9.28, 6.25, 1.15, 7.8, 4.5, 7.56, 16.08, 4.5, 5.0, 2.2, 4.0, 2.51, 4.75, 2.0, 2.1, 6.25, 10.6, 6.0, 0.45, 2.5, 12.75, 30.29, 1.6, 7.54, 6.84, 6.0, 8.0, 24.74, 5.5, 36.0, 11.79, 3.0, 6.75, 1.4, 5.75, 3.4, 4.89, 4.95, 3.49, 3.85, 6.35, 7.08, 38.0, 6.25, 10.15, 10.75, 4.65, 4.75, 7.78, 6.75, 2.99, 2.35, 3.65, 2.74, 3.5, 4.76, 6.2, 2.35, 24.5, 6.0, 3.65, 6.26, 2.1, 32.95, 7.8, 4.25, 4.86, 4.9, 7.06, 4.5, 3.22, 3.25, 4.53, 34.78, 6.5, 2.25, 8.0, 8.37, 5.39, 37.3, 70.8, 22.25, 6.03, 4.9, 3.96, 4.6, 5.5, 3.25, 6.25, 3.0, 4.25, 12.25, 10.95, 16.5, 7.8, 3.7, 4.0, 26.75, 28.03, 5.44, 6.2, 0.9, 3.95, 0.44, 2.75, 7.5, 2.5, 5.0, 3.6, 3.99, 5.64, 12.0, 0.7, 19.0, 30.48, 8.2, 7.55, 0.99, 4.15, 6.2, 4.4, 2.1, 2.2, 8.34, 4.35, 6.8, 3.3, 5.04, 9.2, 5.7, 8.48, 48.0, 6.1, 2.75, 8.0, 1.85, 3.85, 4.74, 5.63, 2.62, 4.9, 2.65, 5.99, 2.4, 4.25, 40.0, 2.7, 2.99, 3.4, 30.8, 5.85, 4.0, 14.12, 4.55, 38.0, 2.9, 6.0, 6.95, 2.75, 5.1, 6.75, 3.69, 5.45, 9.29, 4.0, 2.9, 5.25, 5.75, 13.12, 7.83, 3.15, 10.4, 4.35, 5.23, 6.01, 4.4, 12.75, 2.4, 5.71, 5.49, 1.3, 8.5, 12.99, 5.0, 9.0, 5.22, 3.8, 7.27, 5.1, 29.0, 2.9, 1.38, 5.5, 7.25, 6.98, 5.25, 1.95, 24.5, 8.31, 36.0, 5.5, 5.89, 7.95, 2.75, 6.25, 4.95, 6.27, 8.65, 3.5, 35.0, 4.45, 2.65, 4.7, 8.9, 17.45, 9.58, 6.22, 7.8, 27.75, 7.0, 64.87, 6.5, 2.7, 2.5, 3.9, 3.95, 2.1, 3.5, 2.0, 5.35, 3.8, 17.25, 5.53, 1.95, 8.2, 0.9, 6.5, 19.41, 6.58, 2.1, 2.0, 3.7, 3.8, 3.25, 5.53, 10.9, 5.1, 2.2, 1.6, 11.25, 5.9, 14.4, 3.6, 40.5, 38.95, 3.6, 7.12, 7.52, 10.35, 7.0, 10.85, 2.35, 2.9, 7.65, 6.4, 10.1, 4.25, 19.65, 4.4, 3.25, 2.8, 4.3, 1.55, 4.7, 7.07, 79.0, 5.75, 3.25, 8.89, 5.9, 4.95, 3.75, 10.97, 24.94, 1.97, 1.4, 7.27, 4.0, 4.75, 5.1, 16.11, 10.55, 30.0, 1.6, 18.49, 9.96, 4.75, 3.65, 15.5, 11.82, 2.05, 3.3, 2.25, 20.12, 4.95, 7.48, 5.5, 13.19, 3.85, 5.75, 9.0, 2.21, 8.09, 48.63, 39.47, 22.24, 2.6, 12.0, 18.0, 9.99, 2.45, 8.99, 3.15, 8.2, 11.5, 7.3, 1.59, 3.15, 8.5, 3.0, 21.0, 7.75, 23.0, 13.75, 8.29, 5.79, 30.5, 3.8, 4.45, 3.3, 1.75, 5.5, 13.35, 22.5, 5.25, 3.75, 6.32, 7.75, 1.37, 2.1, 9.3, 12.0, 23.5, 1.8, 12.5, 4.74, 5.43, 31.62, 6.3, 8.45, 5.0, 13.0, 4.7, 93.67, 3.3, 1.51, 6.09, 5.95, 9.0, 4.25, 23.5, 6.35, 3.4, 93.0, 21.6, 4.0, 5.5, 19.25, 3.95, 4.25, 17.02, 6.5, 2.95, 7.12, 11.25, 2.75, 12.0, 3.67, 5.0, 2.3, 2.2, 41.0, 28.5, 5.49, 17.5, 1.99, 6.64, 16.5, 5.0, 5.4, 2.99, 4.1, 6.76, 5.5, 5.99, 2.59, 26.75, 8.5, 23.0, 3.35, 10.75, 6.29, 7.75, 13.5, 3.75, 3.75, 1.5, 1.45, 4.12, 17.11, 10.25, 2.49, 3.85, 6.25, 4.88, 9.45, 4.8, 1.99, 2.8, 22.0, 4.3, 9.75, 5.9, 14.5, 2.4, 2.11, 7.6, 3.6, 6.0, 7.45, 2.1, 5.2, 6.99, 6.36, 11.62, 43.6, 4.9, 6.7, 3.05, 25.0, 19.05, 4.5, 4.15, 11.9, 2.1, 6.95, 2.4, 2.65, 9.0, 2.1, 2.5, 8.95, 34.0, 4.0, 4.45, 1.5, 14.5, 8.41, 5.45, 8.9, 3.65, 29.0, 13.5, 5.4, 5.89, 8.45, 4.0, 45.0, 3.94, 8.0, 4.1, 6.25, 5.25, 83.96, 21.0, 4.3, 5.25, 32.0, 3.9, 2.2, 3.7, 11.27, 2.41, 19.0, 5.8, 13.52, 24.5, 3.25, 56.73, 9.95, 5.5, 25.0, 1.0, 2.15, 7.89, 10.25, 6.0, 7.53, 39.45, 5.84, 8.65, 7.74, 2.5, 5.7, 5.8, 36.5, 9.5, 3.48, 4.55, 3.9, 2.7, 31.0, 10.3, 7.75, 3.2, 4.85, 34.08, 8.1, 2.35, 1.8, 3.42, 5.34, 31.99, 4.75, 6.1, 3.69, 15.0, 14.5, 5.65, 2.5, 38.5, 5.49, 3.55, 10.75, 11.0, 4.5, 8.42, 11.6, 33.63, 2.25, 12.95, 4.25, 25.02, 3.95, 4.4, 4.95, 5.5, 3.25, 4.02, 11.73, 9.5, 8.6, 4.0, 5.55, 2.5, 41.6, 7.41, 6.5, 1.2, 23.0, 2.74, 3.9, 8.0, 4.0, 17.75, 5.05, 12.0, 29.6, 6.5, 4.75, 24.36, 3.2, 3.6, 3.58, 2.5, 3.5, 25.0, 1.75, 10.0, 7.75, 6.45, 10.0, 4.5, 3.4, 4.5, 4.3, 46.0, 3.4, 14.5, 2.1, 3.65, 3.0, 3.95, 6.75, 6.53, 22.0, 4.75, 5.99, 3.05, 2.4, 1.3, 6.71, 7.2, 5.4, 6.63, 7.5, 14.21, 3.0, 5.11, 3.39, 22.99, 2.35, 2.85, 18.5, 5.99, 3.0, 3.6, 24.0, 6.26, 13.7, 35.0, 5.02, 3.1, 5.5, 3.59, 4.65, 3.8, 12.5, 12.9, 2.35, 4.15, 22.58, 2.65, 2.25, 16.0, 19.5, 21.0, 17.5, 2.41, 4.45, 29.93, 1.02, 11.0, 3.5, 5.35, 5.65, 22.0, 5.95, 2.35, 4.1, 5.4, 8.45, 42.5, 10.75, 1.65, 11.03, 3.5, 6.3, 6.75, 7.5, 15.5, 4.65, 7.58, 2.2, 21.0, 5.25, 5.22, 2.0, 9.18, 1.74, 4.45, 4.95, 5.64, 6.9, 13.95, 17.0, 4.6, 5.21, 12.34, 1.5, 22.99, 43.0, 40.0, 1.2, 2.9, 13.9, 7.85, 54.45, 4.75, 3.25, 7.1, 4.65, 5.0, 4.95, 9.8, 78.8, 2.99, 4.45, 0.75, 5.0, 5.0, 9.69, 5.5, 65.0, 5.11, 2.19, 4.25, 14.5, 5.65, 22.5, 1.5, 3.2, 4.5, 4.5, 8.0, 28.9, 4.1, 2.3, 7.22, 5.8, 3.5, 6.35, 8.85, 2.0, 5.5, 2.3, 7.95, 6.16, 2.85, 25.0, 10.36, 26.0, 4.35, 4.5, 5.0, 3.67, 6.0, 6.34, 22.0, 1.67, 7.95, 9.74, 6.0, 21.5, 3.9, 2.35, 2.65, 3.16, 2.05, 2.95, 3.9, 6.68, 3.5, 8.11, 8.3, 45.61, 4.45, 7.85, 3.1, 3.75, 7.65, 4.9, 16.52, 14.05, 6.75, 9.2, 3.0, 2.75, 20.5, 4.25, 6.0, 6.0, 2.41, 7.25, 23.65, 6.5, 18.06, 3.2, 6.42, 23.0, 5.9, 7.75, 15.0, 9.0, 11.5, 6.2, 5.92, 6.29, 4.12, 3.8, 2.7, 20.28, 3.9, 16.5, 3.7, 79.0, 17.99, 3.9, 3.12, 1.65, 3.5, 4.85, 39.22, 2.0, 10.45, 27.0, 2.25, 3.45, 6.14, 2.85, 3.25, 4.0, 2.59, 6.96, 2.19, 3.0, 3.6, 3.7, 21.75, 45.0, 3.19, 6.2, 3.96, 0.82, 4.5, 3.55, 5.5, 10.25, 30.0, 3.5, 3.1, 3.25, 8.99, 3.99, 6.0, 18.25, 7.75, 4.5, 16.75, 17.5, 7.7, 4.45, 5.25, 33.66, 2.8, 8.47, 9.32, 27.43, 6.5, 9.5, 31.8, 4.2, 3.85, 6.0, 1.65, 14.5, 7.1, 28.0, 9.38, 4.78, 1.7, 17.85, 2.75, 5.95, 1.5, 3.8, 38.5, 2.15, 3.75, 8.95, 5.0, 2.95, 10.49, 1.85, 6.45, 5.25, 5.99, 3.82, 39.0, 25.75, 2.2, 2.0, 56.5, 21.0, 4.0, 3.83, 5.89, 1.36, 44.0, 3.26, 8.0, 4.25, 6.0, 16.61, 7.26, 4.0, 34.51, 0.95, 2.2, 5.75, 1.2, 36.75, 10.0, 4.05, 22.0, 27.87, 8.75, 4.79, 11.92, 53.11, 1.15, 7.45, 3.5, 70.15, 19.5, 15.0, 7.57, 4.4, 60.0, 1.6, 4.9, 5.95, 5.35, 5.4, 23.45, 1.9, 6.1, 4.95, 2.5, 3.48, 4.4, 7.99, 10.99, 18.5, 21.69, 5.17, 4.5, 6.75, 3.12, 8.25, 20.14, 12.6, 6.61, 13.23, 4.75, 2.9, 5.5, 9.47, 1.95, 2.2, 1.15, 4.35, 4.5, 3.55, 4.75, 4.52, 12.75, 20.04, 6.5, 7.5, 4.15, 2.5, 5.4, 3.15, 52.5, 5.95, 6.97, 3.2, 1.12, 6.69, 5.9, 2.25, 4.5, 2.61, 11.5, 35.0, 0.5, 5.75, 11.5, 2.75, 31.5, 4.92, 3.52, 17.55, 5.8, 6.95, 2.4, 5.25, 4.25, 1.5, 4.5, 2.5, 1.55, 6.5, 4.96, 3.25, 8.5, 2.75, 3.4, 7.0, 3.21, 14.25, 6.5, 5.49, 0.8, 1.99, 5.91, 6.44, 2.9, 4.6, 2.35, 7.21, 8.0, 3.5, 5.9, 1.74, 6.8, 7.5, 8.0, 5.99, 12.9, 7.0, 35.0, 5.5, 18.46, 2.4, 1.0, 2.65, 5.96, 75.0, 27.15, 10.5, 6.7, 4.9, 8.0, 3.63, 4.8, 4.25, 30.27, 14.25, 3.41, 2.78, 15.5, 3.0, 2.3, 13.28, 2.25, 3.36, 4.25, 4.3, 6.0, 9.18, 4.99, 3.75, 2.5, 7.2, 29.5, 17.55, 12.0, 13.5, 5.1, 10.3, 5.7, 3.41, 2.4, 5.6, 1.0, 8.2, 27.5, 3.5, 4.58, 10.34, 3.25, 5.0, 2.25, 51.52, 8.62, 7.25, 5.47, 31.0, 35.98, 3.42, 11.5, 7.25, 8.0, 7.33, 3.35, 4.4, 2.99, 5.6, 6.63, 7.9, 7.0, 4.95, 9.19, 5.1, 5.9, 9.51, 3.9, 5.39, 3.0, 4.3, 6.75, 4.5, 2.75, 9.0, 2.55, 3.54, 4.25, 1.2, 19.5, 12.0, 3.9, 9.13, 2.25, 3.25, 14.79, 2.35, 3.1, 12.9, 2.5, 3.65, 7.5, 3.74, 5.86, 39.62, 7.05, 7.5, 2.1, 11.6, 19.25, 17.92, 3.6, 4.5, 7.4, 59.29, 5.5, 1.75, 6.75, 3.95, 4.2, 8.4, 8.25, 3.31, 7.5, 4.75, 8.79, 9.5, 1.55, 5.85, 7.52, 3.6, 4.73, 10.5, 34.54, 6.07, 7.76, 7.46, 3.49, 4.05, 11.88, 6.45, 50.0, 9.0, 14.25, 7.36, 4.4, 3.1, 4.28, 5.5, 6.99, 4.29, 4.2, 4.11, 18.75, 64.95, 1.59, 3.6, 7.87, 5.55, 6.4, 2.65, 5.5, 7.31, 7.1, 7.83, 0.85, 3.55, 8.19, 28.0, 13.0, 3.29, 4.41, 4.99, 17.98, 7.71, 2.8, 3.0, 12.49, 5.0, 32.64, 6.5, 35.0, 2.0, 9.46, 39.0, 15.0, 6.15, 14.5, 5.18, 1.24, 2.8, 5.23, 0.45, 3.25, 1.5, 2.85, 4.5, 16.25, 7.75, 4.35, 33.13, 3.63, 4.75, 6.51, 4.8, 6.0, 6.4, 4.9, 20.57, 4.76, 2.0, 9.92, 3.69, 5.75, 5.7, 4.94, 4.29, 3.0, 6.5, 4.9, 5.4, 24.0, 7.46, 9.6, 25.0, 6.8, 8.59, 5.29, 2.5, 13.9, 20.0, 3.4, 5.5, 3.65, 5.86, 10.44, 5.0, 3.37, 6.95, 9.9, 3.3, 50.5, 12.5, 20.5, 14.5, 20.0, 5.25, 5.9, 2.6, 11.0, 15.5, 5.75, 75.0, 2.0, 2.3, 8.2, 4.8, 8.5, 2.9, 6.5, 5.85, 23.91, 7.36, 17.25, 7.0, 17.65, 2.5, 6.0, 8.25, 44.83, 10.5, 1.9, 4.25, 26.5, 22.5, 3.3, 4.3, 5.25, 11.75, 4.25, 14.22, 4.2, 18.25, 18.5, 2.4, 6.5, 3.2, 3.99, 5.45, 2.7, 6.25, 13.28, 3.7, 39.51, 1.4, 3.5, 3.78, 2.7, 3.2, 5.0, 7.0, 2.85, 4.25, 4.9, 16.9, 4.25, 4.34, 17.0, 28.45, 6.15, 9.25, 4.85, 4.8, 2.3, 4.75, 5.0, 2.5, 5.95, 16.0, 6.15, 4.05, 3.1, 5.49, 42.91, 5.7, 2.85, 2.35, 14.76, 2.25, 3.65, 7.25, 10.69, 5.5, 5.1, 3.25, 9.25, 1.7, 2.87, 17.75, 4.5, 2.95, 2.6, 3.0, 15.5, 2.8, 2.5, 5.75, 2.8, 4.59, 3.65, 19.85, 18.5, 6.95, 2.85, 3.75, 2.3, 2.3, 5.95, 3.49, 47.7, 6.43, 4.5, 39.75, 4.0, 6.98, 1.75, 4.75, 23.5, 7.49, 10.85, 3.5, 6.3, 6.75, 28.88, 14.23, 15.0, 5.8, 3.75, 1.15, 12.75, 1.95, 4.95, 8.25, 20.99, 17.5, 5.36, 6.35, 2.95, 55.7, 1.15, 37.5, 4.07, 2.99, 7.9, 7.49, 1.1, 56.0, 3.5, 3.0, 6.1, 2.25, 5.95, 4.95, 5.49, 6.67, 6.25, 1.51, 34.88, 6.9, 5.99, 10.4, 29.0, 5.85, 2.21, 2.4, 3.0, 3.75, 2.95, 5.8, 4.9, 16.95, 12.5, 5.0, 4.68, 29.8, 3.46, 4.0, 4.5, 5.87, 9.5, 32.5, 3.88, 13.08, 3.5, 3.5, 4.45, 2.35, 5.0, 28.0, 2.0, 6.35, 24.63, 3.0, 7.9, 3.25, 8.25, 2.85, 3.2, 1.75, 3.38, 5.75, 4.7, 2.9, 4.25, 14.5, 5.34, 3.85, 8.5, 4.2, 6.75, 26.0, 8.61, 1.46, 2.8, 4.0, 5.47, 2.45, 21.5, 1.38, 13.5, 3.1, 5.49, 9.51, 2.39, 3.25, 5.65, 1.85, 2.02, 5.8, 6.9, 5.35, 2.85, 22.75, 0.45, 4.64, 5.27, 10.0, 3.95, 3.38, 16.8, 1.99, 5.84, 36.15, 25.7, 9.24, 7.65, 25.31, 4.75, 6.69, 3.1, 1.55, 6.84, 1.6, 21.73, 4.75, 2.45, 31.55, 10.25, 27.36, 6.5, 4.25, 5.5, 4.0, 4.65, 28.5, 7.11, 3.9, 5.6, 2.25, 3.9, 28.63, 7.25, 2.0, 3.5, 5.0, 3.72, 3.45, 4.5, 14.36, 5.5, 3.0, 6.08, 5.0, 20.25, 1.2, 18.0, 17.5, 2.1, 7.5, 24.77, 8.65, 35.5, 10.5, 13.0, 26.5, 1.4, 7.51, 4.3, 8.95, 6.91, 9.75, 4.0, 3.65, 10.75, 4.51, 49.22, 3.7, 12.99, 4.15, 4.4, 4.25, 4.25, 7.7, 39.75, 8.5, 7.0, 0.8, 15.25, 2.25, 4.85, 6.42, 2.5, 5.75, 0.5, 11.52, 4.5, 4.75, 13.54, 23.41, 19.25, 20.0, 13.0, 3.99, 4.65, 4.65, 3.15, 8.25, 65.0, 4.5, 17.5, 4.31, 6.2, 4.67, 3.32, 3.75, 4.7, 6.5, 7.25, 8.94, 7.34, 6.9, 5.9, 6.75, 4.1, 27.0, 4.5, 14.5, 5.25, 1.2, 4.95, 7.5, 48.0, 4.45, 59.65, 4.38, 7.9, 1.88, 7.29, 6.0, 6.7, 1.5, 23.8, 7.77, 3.32, 4.94, 11.0, 3.4, 4.17, 1.25, 5.45, 2.59, 12.01, 2.45, 29.0, 2.4, 11.99, 7.9, 6.25, 1.8, 2.8, 4.9, 2.25, 8.89, 15.0, 5.65, 7.0, 2.95, 3.3, 3.5, 2.3, 13.69, 3.1, 12.75, 13.75, 6.75, 5.25, 8.75, 8.87, 6.5, 4.5, 12.5, 16.8, 8.75, 8.5, 2.21, 1.6, 6.25, 2.25, 25.75, 6.75, 6.25, 5.1, 10.75, 5.7, 5.95, 2.4, 3.49, 4.0, 3.85, 3.95, 3.0, 6.7, 6.14, 4.4, 4.25, 25.93, 7.0, 25.12, 4.45, 2.4, 4.33, 6.93, 4.25, 12.5, 4.9, 4.5, 3.0, 5.8, 3.33, 6.62, 5.75, 6.2, 3.5, 2.0, 4.0, 9.5, 17.5, 6.11, 3.75, 6.2, 6.15, 2.4, 2.15, 3.75, 2.15, 4.75, 2.45, 11.15, 8.9, 4.35, 12.0, 8.5, 4.27, 4.25, 9.25, 8.61, 28.0, 9.25, 8.6, 7.53, 5.75, 4.15, 5.84, 16.5, 43.0, 3.55, 8.9, 2.5, 3.85, 7.5, 1.8, 2.25, 24.25, 4.35, 11.5, 4.75, 4.99, 9.15, 13.99, 19.75, 16.77, 2.5, 3.65, 23.5, 3.11, 4.57, 5.32, 3.2, 5.63, 3.0, 9.25, 1.2, 2.15, 3.05, 11.5, 2.3, 4.95, 4.75, 10.15, 2.65, 3.8, 16.68, 5.0, 3.75, 4.11, 4.25, 3.45, 22.5, 4.5, 0.9, 1.85, 3.25, 3.1, 7.34, 4.25, 6.45, 10.75, 27.75, 0.99, 24.0, 6.1, 8.25, 4.65, 9.75, 4.4, 3.99, 45.73, 5.27, 3.5, 7.25, 1.6, 6.0, 3.0, 4.95, 8.99, 1.85, 6.16, 3.5, 4.5, 7.75, 6.6, 4.98, 9.75, 5.55, 10.3, 7.5, 1.8, 6.25, 6.8, 3.0, 11.6, 6.95,

In [ ]:
#replaced_years
#price_list
#kilometers_list
#mileage_list
#seats_list
#power_list
#invalid_power_indices
#engine_list

In [53]:
print(len(replaced_years))
print(len(price_list))
print(len(kilometers_list))
print(len(mileage_list))
print(len(seats_list))
print(len(power_list))
print(len(engine_list))

5975
5975
5975
5975
5975
5975
5975

In [ ]:
('Location', 'Fuel_Type',
       'Transmission', 'Owner_Type']

In [54]:
df.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'Price'],
      dtype='object')

In [55]:
location_list=list(df['Location'])

In [56]:
fuel_type_list=list(df['Fuel_Type'])

In [57]:
transmission_list=list(df['Transmission'])

In [58]:
owner_type_list=list(df['Owner_Type'])

In [59]:
print(len(location_list))
print(len(fuel_type_list))
print(len(transmission_list))
print(len(owner_type_list))

5975
5975
5975
5975

In [60]:
print(len(invalid_power_indices))

103

In [62]:
new_replaced_years=[replaced_years[i] for i in range(len(replaced_years)) if i not in invalid_power_indices]

In [63]:
print(len(new_replaced_years))

5872

In [64]:
new_price_list=[price_list[i] for i in range(len(price_list)) if i not in invalid_power_indices]

In [65]:
new_kilometers_list=[kilometers_list[i] for i in range(len(kilometers_list)) if i not in invalid_power_indices]

In [66]:
new_mileage_list=[mileage_list[i] for i in range(len(mileage_list)) if i not in invalid_power_indices]

In [67]:
new_seats_list=[seats_list[i] for i in range(len(seats_list)) if i not in invalid_power_indices]

In [68]:
new_power_list=[power_list[i] for i in range(len(power_list)) if i not in invalid_power_indices]

In [69]:
new_engine_list=[engine_list[i] for i in range(len(engine_list)) if i not in invalid_power_indices]

In [70]:
new_location_list=[location_list[i] for i in range(len(location_list)) if i not in invalid_power_indices]

In [71]:
new_fuel_type_list=[fuel_type_list[i] for i in range(len(fuel_type_list)) if i not in invalid_power_indices]

In [72]:
new_transmission_list=[transmission_list[i] for i in range(len(transmission_list)) if i not in invalid_power_indices]

In [73]:
new_owner_type_list=[owner_type_list[i] for i in range(len(owner_type_list)) if i not in invalid_power_indices]

In [74]:
new_dataframe=pd.DataFrame(list(zip(new_replaced_years, new_price_list,
                                   new_kilometers_list,new_mileage_list,
                                    new_seats_list,new_power_list,
                                    new_engine_list,new_location_list,
                                    new_fuel_type_list,new_transmission_list,
                                    
                                   new_owner_type_list
                                   )),columns =['Year', 'Price','Kilometers','Mileage',
                                               'Seats','Power','Engine','Location',
                                               'Fuel Type','Transmission','Owner'])

In [75]:
new_dataframe.head()

,Year,Price,Kilometers,Mileage,Seats,Power,Engine,Location,Fuel Type,Transmission,Owner
0,13,1.75,72000.0,26.6,5.0,58.16,998.0,Mumbai,CNG,Manual,First
1,18,12.50,41000.0,19.6,5.0,126.20,1582.0,Pune,Diesel,Manual,First
2,14,4.50,46000.0,18.0,5.0,88.70,1199.0,Chennai,Petrol,Manual,First
3,15,6.00,87000.0,20.7,7.0,88.76,1248.0,Chennai,Diesel,Manual,First
4,16,17.74,40670.0,15.0,5.0,140.80,1968.0,Coimbatore,Diesel,Automatic,Second

In [76]:
new_dataframe.to_csv('modified_car_prices.csv', header=False, index=False)

In [85]:
new_dataframe.head()

,Year,Price,Kilometers,Mileage,Seats,Power,Engine,Location,Fuel Type,Transmission,Owner
0,13,1.75,72000.0,26.6,5.0,58.16,998.0,Mumbai,CNG,Manual,First
1,18,12.50,41000.0,19.6,5.0,126.20,1582.0,Pune,Diesel,Manual,First
2,14,4.50,46000.0,18.0,5.0,88.70,1199.0,Chennai,Petrol,Manual,First
3,15,6.00,87000.0,20.7,7.0,88.76,1248.0,Chennai,Diesel,Manual,First
4,16,17.74,40670.0,15.0,5.0,140.80,1968.0,Coimbatore,Diesel,Automatic,Second

In [87]:
location_set=list(set(list(new_dataframe['Location'])))

In [88]:
fuel_type_set=list(set(list(new_dataframe['Fuel Type'])))

In [90]:
print(fuel_type_set)

['Diesel', 'Petrol', 'CNG', 'LPG']

In [91]:
transmission_set=list(set(list(new_dataframe['Transmission'])))

In [93]:
print(transmission_set)

['Automatic', 'Manual']

In [94]:
owner_set=list(set(list(new_dataframe['Owner'])))
print(owner_set)

['Second', 'Third', 'Fourth & Above', 'First']

In [95]:
print(location_set)

['Pune', 'Mumbai', 'Delhi', 'Ahmedabad', 'Jaipur', 'Kochi', 'Chennai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Coimbatore']

In [96]:
for location in location_set:
    new_dataframe[location]=0

In [97]:
new_dataframe.head()

,Year,Price,Kilometers,Mileage,Seats,Power,Engine,Location,Fuel Type,Transmission,...,Mumbai,Delhi,Ahmedabad,Jaipur,Kochi,Chennai,Bangalore,Kolkata,Hyderabad,Coimbatore
0,13,1.75,72000.0,26.6,5.0,58.16,998.0,Mumbai,CNG,Manual,...,0,0,0,0,0,0,0,0,0,0
1,18,12.50,41000.0,19.6,5.0,126.20,1582.0,Pune,Diesel,Manual,...,0,0,0,0,0,0,0,0,0,0
2,14,4.50,46000.0,18.0,5.0,88.70,1199.0,Chennai,Petrol,Manual,...,0,0,0,0,0,0,0,0,0,0
3,15,6.00,87000.0,20.7,7.0,88.76,1248.0,Chennai,Diesel,Manual,...,0,0,0,0,0,0,0,0,0,0
4,16,17.74,40670.0,15.0,5.0,140.80,1968.0,Coimbatore,Diesel,Automatic,...,0,0,0,0,0,0,0,0,0,0

In [98]:
for fuel in fuel_type_set:
    new_dataframe[fuel]=0

In [99]:
for transmission in transmission_set:
    new_dataframe[transmission]=0

In [100]:
for owner in owner_set:
    new_dataframe[owner]=0

In [101]:
new_dataframe.head()

,Year,Price,Kilometers,Mileage,Seats,Power,Engine,Location,Fuel Type,Transmission,...,Diesel,Petrol,CNG,LPG,Automatic,Manual,Second,Third,Fourth & Above,First
0,13,1.75,72000.0,26.6,5.0,58.16,998.0,Mumbai,CNG,Manual,...,0,0,0,0,0,0,0,0,0,0
1,18,12.50,41000.0,19.6,5.0,126.20,1582.0,Pune,Diesel,Manual,...,0,0,0,0,0,0,0,0,0,0
2,14,4.50,46000.0,18.0,5.0,88.70,1199.0,Chennai,Petrol,Manual,...,0,0,0,0,0,0,0,0,0,0
3,15,6.00,87000.0,20.7,7.0,88.76,1248.0,Chennai,Diesel,Manual,...,0,0,0,0,0,0,0,0,0,0
4,16,17.74,40670.0,15.0,5.0,140.80,1968.0,Coimbatore,Diesel,Automatic,...,0,0,0,0,0,0,0,0,0,0

In [105]:
new_dataframe.columns

Index(['Year', 'Price', 'Kilometers', 'Mileage', 'Seats', 'Power', 'Engine',
       'Location', 'Fuel Type', 'Transmission', 'Owner', 'Pune', 'Mumbai',
       'Delhi', 'Ahmedabad', 'Jaipur', 'Kochi', 'Chennai', 'Bangalore',
       'Kolkata', 'Hyderabad', 'Coimbatore', 'Diesel', 'Petrol', 'CNG', 'LPG',
       'Automatic', 'Manual', 'Second', 'Third', 'Fourth & Above', 'First'],
      dtype='object')

In [107]:
for i in range(len(new_dataframe)):
    new_dataframe.loc[i,new_dataframe.loc[i, "Location"]]=1

In [110]:
for i in range(len(new_dataframe)):
    new_dataframe.loc[i,new_dataframe.loc[i, "Fuel Type"]]=1

In [111]:
for i in range(len(new_dataframe)):
    new_dataframe.loc[i,new_dataframe.loc[i, "Transmission"]]=1

In [112]:
for i in range(len(new_dataframe)):
    new_dataframe.loc[i,new_dataframe.loc[i, "Owner"]]=1

In [113]:
new_dataframe.head()

,Year,Price,Kilometers,Mileage,Seats,Power,Engine,Location,Fuel Type,Transmission,...,Diesel,Petrol,CNG,LPG,Automatic,Manual,Second,Third,Fourth & Above,First
0,13,1.75,72000.0,26.6,5.0,58.16,998.0,Mumbai,CNG,Manual,...,0,0,1,0,0,1,0,0,0,1
1,18,12.50,41000.0,19.6,5.0,126.20,1582.0,Pune,Diesel,Manual,...,1,0,0,0,0,1,0,0,0,1
2,14,4.50,46000.0,18.0,5.0,88.70,1199.0,Chennai,Petrol,Manual,...,0,1,0,0,0,1,0,0,0,1
3,15,6.00,87000.0,20.7,7.0,88.76,1248.0,Chennai,Diesel,Manual,...,1,0,0,0,0,1,0,0,0,1
4,16,17.74,40670.0,15.0,5.0,140.80,1968.0,Coimbatore,Diesel,Automatic,...,1,0,0,0,1,0,1,0,0,0

In [114]:
del new_dataframe['Location']
del new_dataframe['Fuel Type']
del new_dataframe['Transmission']
del new_dataframe['Owner']

In [115]:
new_dataframe.columns

Index(['Year', 'Price', 'Kilometers', 'Mileage', 'Seats', 'Power', 'Engine',
       'Pune', 'Mumbai', 'Delhi', 'Ahmedabad', 'Jaipur', 'Kochi', 'Chennai',
       'Bangalore', 'Kolkata', 'Hyderabad', 'Coimbatore', 'Diesel', 'Petrol',
       'CNG', 'LPG', 'Automatic', 'Manual', 'Second', 'Third',
       'Fourth & Above', 'First'],
      dtype='object')

In [116]:
x=new_dataframe[['Year','Kilometers','Mileage','Seats','Power','Engine',
                'Pune','Mumbai','Delhi','Ahmedabad','Jaipur','Kochi','Chennai',
                'Bangalore','Kolkata','Hyderabad','Coimbatore','Diesel','Petrol',
                'CNG','LPG','Automatic','Manual','Second','Third','Fourth & Above',
                'First']]

In [117]:
y=new_dataframe['Price']

In [118]:
from sklearn.model_selection import train_test_split

In [120]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [123]:
from sklearn import datasets, linear_model, metrics
reg = linear_model.LinearRegression() 
reg.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [124]:
print('Coefficients: \n', reg.coef_)

Coefficients:
 [ 8.92666235e-01 -3.21485992e-05 -2.16703399e-01 -1.07273487e+00
  1.26563811e-01  9.06132695e-04  9.98167161e-02 -1.57448875e+00
 -7.83897582e-01 -4.72238640e-01  6.63582080e-01 -8.97012289e-01
  5.63232058e-01  9.29418088e-01 -1.71284020e+00  1.64600021e+00
  1.53842830e+00 -1.99863438e-01 -3.04240966e+00  1.40057218e+00
  1.84170092e+00  1.05395970e+00 -1.05395970e+00 -3.84528575e-01
  5.67261508e-01  2.72696075e-02 -2.10002540e-01]

In [126]:
print('Variance score: {}'.format(reg.score(x_test, y_test)))

Variance score: 0.3890819863669405

In [127]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0) 
regressor.fit(x_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [128]:
y_pred = regressor.predict(x_test)

In [132]:
import sklearn.metrics

In [134]:
print(sklearn.metrics.r2_score(y_test,y_pred))

0.8130695527633435

In [135]:
import pickle

In [136]:
outfile = open('CarPricePrediction.pkl','wb')
pickle.dump(regressor,outfile)
outfile.close()

NameError: name 'pd' is not defined